### ISSUE TITLE
No way to add multiple labels without duplicating test lists?

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt-metadata#2308]
I'd like to have both the `interop-2022-rfc` and `interop-2022-forms` labels in a bunch of places, like here:

https://github.com/web-platform-tests/wpt-metadata/blob/233aab4846cedb5d1308ff6db2bce137085bd2f6/html/semantics/forms/constraints/META.yml#L19-L41

It looks like the only way to do this is to duplicate the whole block. I would like to be able to do this:
```yaml
    - label: ['interop-2022-rfc', 'interop-2022-forms']
      results:
        - test: ...
```

This would really only work when editing the YAML by hand however, or the code for updating YAML would need to check if an existing label labels exactly the same tests and then merge the blocks.

@KyleJu WDYT?
