### ISSUE TITLE
Directory labels are ignored when a file-specific label is applied

### ISSUE THREAD

**Issue by cookiecrook** [web-platform-tests/wpt-metadata#4665]
Source excerpt from [`./inert/META.yml`](https://github.com/web-platform-tests/wpt-metadata/blob/master/inert/META.yml)

```yml
links:
    - label: a11y
      results:
        - test: "*"
    - label: accessibility
      results:
        - test: "*"
    - label: inert
      results:
        - test: "*"
```

The above works mostly as expected in this directory and others, applying all three labels to descendant files in the directory. However, when there is a file-specific label applied, the directories labels are overwritten.

```yml
    - label: interop-2023-inert
      results:
        - test: dynamic-inert-on-focused-element.html
        - test: inert-computed-style.html
        - test: inert-on-non-html.html
        - test: inert-on-slots.html
        - test: inert-with-modal-dialog-001.html
        - test: inert-canvas-fallback-content.html
        - test: inert-iframe-hittest.html
        - test: inert-iframe-tabbing.html
        - test: inert-label-focus.html
        - test: inert-node-is-uneditable.html
        - test: inert-node-is-unselectable.html
        - test: inert-with-modal-dialog-002.html
        - test: inert-inlines.html
        - test: inert-node-is-unfocusable.html
        - test: inert-pseudo-element-hittest.html
        - test: inert-svg-hittest.html
        - test: inert-and-contenteditable.html
        - test: inert-does-not-match-disabled-selector.html
        - test: inert-in-shadow-dom.html
```

In short, the above files do not show up in the following search, but should.

https://wpt.fyi/results/inert?label=master&label=experimental&aligned&q=label%3Aaccessibility

The only file that shows up in the results is the one without a file-specific label block test reference.
